"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$status\
$character"""

[git_branch]
style = 'purple'
ignore_branches = ['main', 'master']
format = '[$branch(:$remote_branch)]($style) '

[status]
disabled = false
