.TH "DOT_INSTALL" "1" "Apr 2026" "dotfiles" "dotfiles"
.SH NAME
dot_install \- sets up dotfiles
.SH SYNOPSIS
.B dot_install
.br
.B dot_install
\fBupdate\fR
.br
.B dot_install
\fBcheck\fR
.br
.B dot_install
\fIname\fR
.SH DESCRIPTION
.B dot_install
sets up dotfiles.
.PP
When called with no arguments, it installs config files.
.PP
With \fBupdate\fR, it fetches the latest changes and installs them.
.PP
With \fBcheck\fR, it prints optional setup commands in the form of `\fBdot_install\fR \fIname\fR`
