.TH "DOT_INSTALL" "1" "Apr 2026" "dotfiles" "dotfiles"
.SH NAME
dot_install \- sets up dotfiles
.SH SYNOPSIS
.B dot_install
.br
.B dot_install
\fBupdate\fR
.br
.B dot_install
\fIname\fR
.SH DESCRIPTION
.B dot_install
sets up dotfiles. It installs config files in ~/.config and ~/.local/share.
.PP
With \fBupdate\fR, it fetches the latest changes before installing.
.PP
With \fIname\fR, it sets up optional configuration. The available options are printed after running \fBdot_install\fR.
