# See https://starship.rs/config/
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 30
format = '$directory$git_branch$git_state$cmd_duration$python$shell$shlvl$character'

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
truncation_length = 20
ignore_branches = [ "main", "master" ]

[python]
format = "([$virtualenv]($style) )"

[shell]
disabled = false
bash_indicator = 'bash '
fish_indicator = ''
zsh_indicator = 'zsh '
style = 'dimmed'
format = '[$indicator]($style)'

[shlvl]
disabled = false
repeat = true
symbol = '❯'
repeat_offset = 1
style = 'bold green'
format = '[$symbol]($style)'
