brew "bat"
brew "eza"
brew "fd"
brew "fish" if OS.mac?
cask "font-jetbrains-mono-nerd-font" if OS.mac?
brew "fzf"
brew "gitui"
brew "helix"
brew "htop"
brew "mise"
brew "patchutils" if OS.mac?
brew "ripgrep"
brew "starship"
brew "wget" if OS.mac?
brew "zoxide"

# LSPs
brew "bash-language-server"
brew "fish-lsp"
brew "marksman" # markdown
brew "ruff" # python
brew "rust-analyzer"
brew "shellcheck" # works with bash-languae-server
brew "shfmt" # works with bash-languae-server
brew "taplo" # toml
brew "typescript-language-server"
brew "vscode-langservers-extracted" # css, html, json
brew "yaml-language-server"
