name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 2 * * *' # daily at 02:00

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    permissions:
      # required for git-auto-commit-action
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v1
      - uses: DeterminateSystems/update-flake-lock@v19
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update flake.lock
