name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 2 * * *' # daily at 02:00

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v1
      - id: update
        uses: DeterminateSystems/update-flake-lock@v19
      - name: Merge
        run: gh pr merge "$PR_NUM" --rebase
        env:
          PR_NUM: ${{ steps.update.outputs.pull-request-number }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
